### ISSUE TITLE
Failed at 'webpack --config webpack.config.js'

### ISSUE THREAD

**Issue by ONIXTurtle** [mozilla-mobile/firefox-ios#3920]
Hey there after running sh bootstrap i'm getting the error:
`Failed at the firefox-ios@1.0.0 build script 'webpack --config webpack.config.js'.
npm ERR! This is most likely a problem with the firefox-ios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs firefox-ios
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls firefox-ios
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:`
and here is the npm error : `0 info it worked if it ends with ok
1 verbose cli [ '/Users/torstenhogel/.nvm/v0.10.48/bin/node',
1 verbose cli   '/Users/torstenhogel/.nvm/v0.10.48/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.1
3 info using node@v0.10.48
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild firefox-ios@1.0.0
6 info build firefox-ios@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info firefox-ios@1.0.0 Failed to exec build script
9 verbose stack Error: firefox-ios@1.0.0 build: `webpack --config webpack.config.js`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/Users/torstenhogel/.nvm/v0.10.48/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid firefox-ios@1.0.0
11 verbose cwd /Users/torstenhogel/Documents/app/Go-On Network/ios/firefox-ios
12 error Darwin 17.5.0
13 error argv "/Users/torstenhogel/.nvm/v0.10.48/bin/node" "/Users/torstenhogel/.nvm/v0.10.48/bin/npm" "run" "build"
14 error node v0.10.48
15 error npm  v2.15.1
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error firefox-ios@1.0.0 build: `webpack --config webpack.config.js`
20 error spawn ENOENT
21 error Failed at the firefox-ios@1.0.0 build script 'webpack --config webpack.config.js'.
21 error This is most likely a problem with the firefox-ios package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     webpack --config webpack.config.js
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs firefox-ios
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls firefox-ios
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
`

**Comment by farhanpatel** [comment]
Closing due to inactivity. Please reopen if you feel it is still is relevant
