### ISSUE TITLE
I have a problem when use "sh ./bootstrap.sh ",Can someone help me.

### ISSUE THREAD

**Issue by AlanJDL** [mozilla-mobile/firefox-ios#5421]
Here is the log:
> firefox-ios@1.0.0 build /Users/macbook/Desktop/firefox/firefox-ios
> webpack --config webpack.config.js

/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

TypeError: Object.entries is not a function
    at Object.<anonymous> (/Users/macbook/Desktop/firefox/firefox-ios/webpack.config.js:23:34)
    at Module._compile (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (native)
    at module.exports (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse.err (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/yargs/yargs.js:563:18)
    at /Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbook/Desktop/firefox/firefox-ios/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firefox-ios@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firefox-ios@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook/.npm/_logs/2019-09-09T07_43_23_629Z-debug.log
Fingerprinting blacklist has 137 entries.
Cryptomining blacklist has 69 entries.
Content blacklist has 514 entries.
Analytics blacklist has 300 entries.
Advertising blacklist has 1649 entries.
Social blacklist has 67 entries.
Fingerprinting blacklist has 137 entries.
Cryptomining blacklist has 69 entries.
Content blacklist has 514 entries.
Analytics blacklist has 300 entries.
Advertising blacklist has 1649 entries.
Social blacklist has 67 entries.

**Comment by garvankeeley** [comment]
my versions of things are:
```
$ npm -v
6.9.0
$ node -v
v11.14.0
```
what are yours?

**Comment by AlanJDL** [comment]
Problem solved
